# app/mock_profiles.py

mock_users = [
    {
        "username": "rahul@gmail.com",
        "schedule": "Night owl",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook daily at home",
        "work_mode": "Mix of home and outside",
        "stress": "Talk it out with others",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Middle floors (balanced)",
        "spot": "Near window (natural light)",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "anjali@gmail.com",
        "schedule": "Early bird",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Always work/study from home",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Prefer to keep things low-key",
        "floor": "Top floor (better view/privacy)",
        "spot": "Near door (easy access)",
        "sunlight": "Shaded/cooler room"
    },
    {
        "username": "neha@yahoo.com",
        "schedule": "Moderate",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Mix of home and outside",
        "stress": "Need some space first, then talk",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Prefer to keep things low-key",
        "floor": "Middle floors (balanced)",
        "spot": "No preference",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "amit@hotmail.com",
        "schedule": "Early bird",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook daily at home",
        "work_mode": "Always work/study from home",
        "stress": "Talk it out with others",
        "personality": "Extrovert (love social interaction)",
        "conversation": "Love regular chats and bonding",
        "conflict": "Address immediately and talk it out",
        "celebration": "Love celebrating together",
        "floor": "Ground floor (easy access)",
        "spot": "Near window (natural light)",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "sara@gmail.com",
        "schedule": "Night owl",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Prefer to keep things low-key",
        "floor": "Top floor (better view/privacy)",
        "spot": "No preference",
        "sunlight": "Shaded/cooler room"
    },
    {
        "username": "deepak@yahoo.com",
        "schedule": "Moderate",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Mix of home and outside",
        "stress": "Need some space first, then talk",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Middle floors (balanced)",
        "spot": "Near door (easy access)",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "kavya@gmail.com",
        "schedule": "Early bird",
        "tidiness": "Somewhat tidy",
        "environment": "Need complete silence",
        "cooking": "Cook daily at home",
        "work_mode": "Always work/study from home",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Occasional small celebrations",
        "floor": "Ground floor (easy access)",
        "spot": "Near window (natural light)",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "vikas@outlook.com",
        "schedule": "Night owl",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Talk it out with others",
        "personality": "Extrovert (love social interaction)",
        "conversation": "Love regular chats and bonding",
        "conflict": "Address immediately and talk it out",
        "celebration": "Love celebrating together",
        "floor": "Top floor (better view/privacy)",
        "spot": "No preference",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "priya@yahoo.com",
        "schedule": "Early bird",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Mix of home and outside",
        "stress": "Need some space first, then talk",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Middle floors (balanced)",
        "spot": "Near door (easy access)",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "siddharth@gmail.com",
        "schedule": "Night owl",
        "tidiness": "Somewhat tidy",
        "environment": "Need complete silence",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Prefer to handle alone",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Prefer to keep things low-key",
        "floor": "Middle floors (balanced)",
        "spot": "No preference",
        "sunlight": "Shaded/cooler room"
    },
    {
        "username": "megha@hotmail.com",
        "schedule": "Moderate",
        "tidiness": "Super organized",
        "environment": "Some background noise is okay",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Always work/study from home",
        "stress": "Talk it out with others",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Top floor (better view/privacy)",
        "spot": "Near window (natural light)",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "rohit@protonmail.com",
        "schedule": "Night owl",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Take time to think, then discuss",
        "celebration": "Prefer to keep things low-key",
        "floor": "Ground floor (easy access)",
        "spot": "Near door (easy access)",
        "sunlight": "Shaded/cooler room"
    },
    {
        "username": "tanvi@gmail.com",
        "schedule": "Moderate",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Always work/study from home",
        "stress": "Prefer to handle alone",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Middle floors (balanced)",
        "spot": "Near door (easy access)",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "arjun@gmail.com",
        "schedule": "Night owl",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook daily at home",
        "work_mode": "Mix of home and outside",
        "stress": "Need some space first, then talk",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Love regular chats and bonding",
        "conflict": "Address immediately and talk it out",
        "celebration": "Love celebrating together",
        "floor": "Top floor (better view/privacy)",
        "spot": "Near window (natural light)",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "shruti@outlook.com",
        "schedule": "Early bird",
        "tidiness": "Somewhat tidy",
        "environment": "Some background noise is okay",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Prefer to keep things low-key",
        "floor": "Ground floor (easy access)",
        "spot": "Near door (easy access)",
        "sunlight": "Shaded/cooler room"
    },
    {
        "username": "dev@gmail.com",
        "schedule": "Moderate",
        "tidiness": "Super organized",
        "environment": "Need complete silence",
        "cooking": "Cook daily at home",
        "work_mode": "Always work/study from home",
        "stress": "Prefer to handle alone",
        "personality": "Introvert (prefer solitude)",
        "conversation": "Prefer privacy and minimal interaction",
        "conflict": "Prefer to avoid direct conflict",
        "celebration": "Prefer to keep things low-key",
        "floor": "Middle floors (balanced)",
        "spot": "Near window (natural light)",
        "sunlight": "Moderate sunlight"
    },
    {
        "username": "aisha@gmail.com",
        "schedule": "Night owl",
        "tidiness": "Somewhat tidy",
        "environment": "Need complete silence",
        "cooking": "Mostly order in/eat out",
        "work_mode": "Prefer libraries/cafes/office",
        "stress": "Talk it out with others",
        "personality": "Extrovert (love social interaction)",
        "conversation": "Love regular chats and bonding",
        "conflict": "Address immediately and talk it out",
        "celebration": "Love celebrating together",
        "floor": "Top floor (better view/privacy)",
        "spot": "Near window (natural light)",
        "sunlight": "Sunny room (lots of natural light)"
    },
    {
        "username": "manav@gmail.com",
        "schedule": "Early bird",
        "tidiness": "Super organized",
        "environment": "Some background noise is okay",
        "cooking": "Cook 3–4 times per week",
        "work_mode": "Mix of home and outside",
        "stress": "Prefer to handle alone",
        "personality": "Ambivert (balanced social needs)",
        "conversation": "Occasional friendly conversation",
        "conflict": "Take time to think, then discuss",
        "celebration": "Occasional small celebrations",
        "floor": "Middle floors (balanced)",
        "spot": "Near window (natural light)",
        "sunlight": "Moderate sunlight"
    }
]
